# GoSql测试配置文件

# 大语言模型配置
llm:
  # 提供商: openai, azure, gemini, local
  provider: "openai"
  # 模型名称
  model: "deepseek-r1-250120"
  # 温度参数，控制生成的随机性
  temperature: 0.3
  # 最大生成token数
  max_tokens: 2048
  
  # OpenAI配置
  openai:
    # API密钥 - 警告：切勿提交真实密钥到版本控制系统
    api_key: "YOUR_OPENAI_API_KEY_HERE"
    # API基础URL
    base_url: "https://ark.cn-beijing.volces.com/api/v3"
  
# 评估配置
eval:
  # 评估方法: exec, semantic
  method: "exec"
  # 数据库目录
  db_dir: "./data/spider/database"

# 数据集配置
dataset:
  # Spider数据集目录
  spider_dir: "./data/spider"
  # C-Spider数据集目录
  cspider_dir: "./data/cspider"
